import type { Profile } from "@/types/profile";

export const PROFILES: Profile[] = [
  {
    name: "Satoshi Nakamoto",
    handle: "satoshi",
    role: "Builder",
    bio: "Bitcoin creator and blockchain pioneer. Apasionado de los sistemas descentralizados.",
    tags: ["Bitcoin", "Cryptography", "P2P Systems"],
    location: "Global",
    available: true,
    avatar: "https://i.pravatar.cc/100?img=5",
  },
  {
    name: "Vitalik Buterin",
    handle: "vitalik",
    role: "Founder",
    bio: "Ethereum co-founder. Enfocado en soluciones de escalado y el futuro de Web3.",
    tags: ["Ethereum", "Smart Contracts", "Solidity"],
    location: "Singapore",
    available: false,
    avatar: "https://i.pravatar.cc/100?img=15",
  },
  {
    name: "Alice Johnson",
    handle: "alice_dev",
    role: "Developer",
    bio: "Full-stack especializada en protocolos DeFi. Disponible para consultoría.",
    tags: ["Solidity", "React", "Node.js"],
    location: "New York, USA",
    available: true,
    avatar: "https://i.pravatar.cc/100?img=32",
  },
  {
    name: "Bob Williams",
    handle: "crypto_marketer",
    role: "Marketer",
    bio: "Growth marketer con 5+ años en cripto. Ha lanzado 10+ proyectos exitosos.",
    tags: ["Growth Marketing", "Community", "Social Media"],
    location: "London, UK",
    available: false,
    avatar: "https://i.pravatar.cc/100?img=66",
  },
  {
    name: "Sarah Chen",
    handle: "nft_artist",
    role: "Designer",
    bio: "Artista digital enfocada en colecciones NFT. Más de 1000 piezas vendidas.",
    tags: ["NFT Design", "Illustration", "Photoshop"],
    location: "Tokyo, Japan",
    available: true,
    avatar: "https://i.pravatar.cc/100?img=12",
  },
  {
    name: "Michael Davis",
    handle: "venture_cap",
    role: "Investor",
    bio: "Inversionista en XYZ Capital. Buscando proyectos Web3 en etapa temprana.",
    tags: ["Venture Capital", "Due Diligence", "Token Economics"],
    location: "San Francisco, USA",
    available: false,
    avatar: "https://i.pravatar.cc/100?img=1",
  },
];
