[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Empaqueta los binarios de Prisma dentro de las functions
[[plugins]]
  package = "netlify-plugin-prisma"
  [plugins.inputs]
    generate = true
