[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

# Activa el runtime oficial de Next.js en Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client"]
  included_files = [
    "node_modules/.prisma/**",
    "prisma/schema.prisma"
  ]
